### ISSUE TITLE
Paste Notes adds linebreak at end of paste, highlights all notes afterward

### ISSUE THREAD

**Issue by MShayOffice** [DoubleDee73/Yass#18]
I'm on v2024.10 on Window 10.

To reproduce:
- Copy notes

![image](https://github.com/user-attachments/assets/12f1d71c-5dfb-4f92-b12b-a5f2639c7c24)

- Select notes elsewhere

![image](https://github.com/user-attachments/assets/b5054b5a-ade4-4dc3-8e15-5a8a5707c855)

- Use the "Paste Notes" option through the menu or with Ctrl+Shift+V

![image](https://github.com/user-attachments/assets/d262aecd-6f8d-4645-8f4c-fdca939c6090)

After doing Paste Notes, an extra line break has been added at the end of the pasted text, and all following text has been highlighted.

**Comment by MShayOffice** [comment]
Personally, I would expect the "Paste Notes" behaviour to work like it does in a text editor.
Pasting on its own will delete any highlighted notes, and insert the copied notes at the cursor.

Right now it seems to behave a couple different ways depending on how many rows have been copied and how many syllables are in those rows. I don't even think it's working the same way as the other Paste options, where they paste over the same number of copied syllables, regardless of line breaks.

It makes sense that it would behave differently, since Paste Melody and Paste Note Heights are more effecting the note metadata and isn't able to create/remove/rewrite the notes themselves, but it's currently behaving in a way I find unpredictable, and I think it was working differently+better before the last update.

**Comment by DoubleDee73** [comment]
I can fix the page break, but can you specify what exactly you think worked differently/better before the last update? @MShayOffice

**Comment by MShayOffice** [comment]
Until the 2024-10 update, I never experienced the behaviour where pasting notes would select all remaining notes through the end of the song.

It's possible it's always behaved this way and I was never using Paste Notes in this exact way until that time, and it was all a coincidence, but once I noticed this and started experimenting, I got more and more confused with how Paste Notes works.

**Comment by DoubleDee73** [comment]
I'm still not exactly sure, if I understand correctly. But it's possible, that you are confusing the behaviour with the way the original Yass did it. There pasting notes, would simply paste the notes "over" the selected notes, but also leaving the original notes, where they were. I thought, that was confusing af. I sorta changed it so that it was more in line how the USDX editor does it: You select the first note from which the pasting starts, and it will then simply paste over everything for the length of the copied section, regardless whether you have selected one or more notes.
I could adjust the behaviour, so that it would only paste over the length of selected notes, but to be honest, I have never had the situation, where I thought this would be useful.
I am using "Paste Notes" all the time, and quite honestly, I find it extremely useful the way it works now.
The one thing, that I have now changed is, that when you copied a section where the last note is followed by a page break, then when you paste it somewhere, then the page break will be added as well. If the last note you copy is followed by a regular note, then it will not add a page break.
The way I used it was copying and pasting choruses and stuff, and those would always end with a page break anyway, so that never bothered me.
ping @MShayOffice

**Comment by DoubleDee73** [comment]
Aha, now I understand, you mean that the selection of notes prior to pasting is lost, and that after pasting, all notes are selected. This was already the case before 2024.10. Just tried it with 2024.9. Don't know, when that came in, but this must be some behaviour that is done implicitly. I am now "saving" the selection before pasting, and re-applying the selection after pasting.

**Comment by MShayOffice** [comment]
Thanks. Sorry if my description was confusing. I haven't worked with other tools like this, so I don't know what the standard behaviour would be. I just assumed that if I selected some notes before hitting Paste Notes, it would replace everything I've selected with whatever I'm pasting in, similar to a text editor.

If people are used to the way it currently works and have built workflows around it, I wouldn't want to mess that up too much, but changing the selection so drastically after pasting seemed odd. If anything, I would expect it to select all the newly-pasted notes, to make it clear what's been changed.
