### ISSUE TITLE
Feature Request - Adjust delay before hearing Instrument

### ISSUE THREAD

**Issue by MShayOffice** [DoubleDee73/Yass#19]
I don't know if this board is for bugs only, or if feature requests are considered, but there's quite a delay between the note position and the instrument sound when the keyboard is up. The timing is much more accurate with the ticks, but the instrument is ~120ms off from what I can tell. Perhaps the sample is being triggered at the right time, but that's the start of the clip and not the peak of the piano sample's attack.

If intentional, I imagine this is so you can hear the sung note and the instrument back-to-back to compare them, but when playing back large portions of a song it can be handy to hear them overlaid to see how well the timing lines up.

Would it be possible to add a Preferences option to adjust this offset? Or if there is no built-in offset and it's just caused by extra MIDI processing, then maybe an option to introduce a negative offset, so we can tune the instrument timing to line up with the song?

Also, it would be nice to be able to still hear the clicks while the instrument is playing. There's a menu item for it, so it would make sense for it to be able to be toggled separately.

**Comment by DoubleDee73** [comment]
Funny you mentioned that. I actually sampled sounds from my keyboard for all 88 notes and worked on playing these samples instead of the MIDI notes. The problem with the MIDI sequencer is, that there was no intentional gap between triggering playback and the actual note being heard. Furthermore, I don't know, if the gap is the same on each machine.
In anycase, this has now been addressed and should be ready to be released in November
